### PR TITLE
CRE-232 upgrade qs version

### PR DESCRIPTION
**Pull request by ilasahu**

### CODE REVIEW

**Comment by Walter-Felix** [comment]
What is `qs`? Did you check that changing the version has no side effects and everything still works?

**Comment by ilasahu** [comment]
> What is `qs`? Did you check that changing the version has no side effects and everything still works?

It's an npm package that we are using and the dependabot was showing an error to update it.
 Yes, I did check in the organization, and there was only a repo using it `jimdo/catwalk`. And I checked by updating that too.

**Comment by Walter-Felix** [comment]
> And I checked by updating that too.

I'm not sure if I understand correctly. You updated `jimdo/catwalk` to use the update of this repo and you started `catwalk` locally and tested that the update has no side effects?

Additionally I'm wondering if we could just get rid of this repository. The functionality  is suuuper simple and it's only used by one other repo. It would be an opportunity to reduce the number of repos we are responsible for.

**Comment by ilasahu** [comment]
> I'm not sure if I understand correctly. You updated `jimdo/catwalk` to use the update of this repo and you started `catwalk` locally and tested that the update has no side effects?

@Walter-Felix 
Since this repo was not updated we cannot use the updated version of this repo in the catwalk. So, I made the same changes in `jimdo/catwalk` that I've done here to check if works as expected.

Yes, sure! I'll check if we can remove this repo. I'll create another ticket for this. Should I close this pull request for now?

**Comment by Walter-Felix** [comment]
> Should I close this pull request for now?

As you tested the update, I will approved the PR and we can merge it. Afterwards with the new ticket we can validate if we can get rid of this repo. How does this sound to you?

**Review by Walter-Felix — APPROVED** [review]

**Comment by ilasahu** [comment]
> > Should I close this pull request for now?
> 
> As you tested the update, I will approved the PR and we can merge it. Afterwards with the new ticket we can validate if we can get rid of this repo. How does this sound to you?

Sounds good :)

**Pull request merged**
